name: Example of axios action
on: [ push ]
jobs:
    test-axios-action:
        name: 'Perform REST API Test'
        runs-on: ubuntu-latest
        steps:
            - name: Run test
              run: npm test