name: Example of axios action
on: [ push ]
jobs:
    test-axios-action:
        name: 'Perform REST API Test'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Run test
              run: npm run test